---

- hosts: all
  become: true
  tasks:

  - name: Install apache package and add php support for CentOS
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: Install apache package and add php support for Ubuntu
    apt:    
      name:
        - apche2                 
        - libapache2-mod-php                
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
       
