---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
 
       
